apiVersion: v1
kind: Pod
metadata:
  name: django-uses-operator
  annotations:
    instrumentation.opentelemetry.io/inject-python: "true"
spec:
  containers:
  - name: server
    image: docker.io/jennydaman/djangoexamplepear:latest
    imagePullPolicy: Always
  terminationGracePeriodSeconds: 1
